spring:
  application:
    name: Demo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 7071
  servlet:
    context-path: /
data:
  mysql:
    url: jdbc:mysql://localhost:3306/local?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: p@ssw0rd
  postgre:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: p@ssw0rd